import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { QueryProvider } from "@/config/query-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ModalManager } from "@/components/modal/modal-manager";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Suspense>
          <QueryProvider>
            <NuqsAdapter>
              <ModalManager />
              {children}
            </NuqsAdapter>
          </QueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
